version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/go:1.16.5'
    steps:
      - checkout
      - run:
          name: Echo command
          command: 'echo "Hello, CircleCI"'
      - run: ls -al
