# permissions for end users to edit acmautosyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acmautosync-editor-role
rules:
- apiGroups:
  - acm-autosync.io
  resources:
  - acmautosyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - acm-autosync.io
  resources:
  - acmautosyncs/status
  verbs:
  - get
