# permissions for end users to view acmautosyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acmautosync-viewer-role
rules:
- apiGroups:
  - acm-autosync.io
  resources:
  - acmautosyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - acm-autosync.io
  resources:
  - acmautosyncs/status
  verbs:
  - get
