
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - acm-autosync.io
  resources:
  - acmautosyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - acm-autosync.io
  resources:
  - acmautosyncs/finalizers
  verbs:
  - update
- apiGroups:
  - acm-autosync.io
  resources:
  - acmautosyncs/status
  verbs:
  - get
  - patch
  - update
