//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmAutoSync) DeepCopyInto(out *AcmAutoSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmAutoSync.
func (in *AcmAutoSync) DeepCopy() *AcmAutoSync {
	if in == nil {
		return nil
	}
	out := new(AcmAutoSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcmAutoSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmAutoSyncList) DeepCopyInto(out *AcmAutoSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcmAutoSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmAutoSyncList.
func (in *AcmAutoSyncList) DeepCopy() *AcmAutoSyncList {
	if in == nil {
		return nil
	}
	out := new(AcmAutoSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcmAutoSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmAutoSyncSpec) DeepCopyInto(out *AcmAutoSyncSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmAutoSyncSpec.
func (in *AcmAutoSyncSpec) DeepCopy() *AcmAutoSyncSpec {
	if in == nil {
		return nil
	}
	out := new(AcmAutoSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmAutoSyncStatus) DeepCopyInto(out *AcmAutoSyncStatus) {
	*out = *in
	in.SecretCreationTime.DeepCopyInto(&out.SecretCreationTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmAutoSyncStatus.
func (in *AcmAutoSyncStatus) DeepCopy() *AcmAutoSyncStatus {
	if in == nil {
		return nil
	}
	out := new(AcmAutoSyncStatus)
	in.DeepCopyInto(out)
	return out
}
